/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsNewRouteImport } from './routes/bills.new'
import { Route as BillsIdRouteImport } from './routes/bills.$id'
import { Route as BillsIdEditRouteImport } from './routes/bills.$id.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsNewRoute = BillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdEditRoute = BillsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BillsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/setup': typeof SetupRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/new': typeof BillsNewRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/setup': typeof SetupRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/new': typeof BillsNewRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/setup': typeof SetupRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/new': typeof BillsNewRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/setup'
    | '/bills/$id'
    | '/bills/new'
    | '/bills/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/setup'
    | '/bills/$id'
    | '/bills/new'
    | '/bills/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/setup'
    | '/bills/$id'
    | '/bills/new'
    | '/bills/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  SetupRoute: typeof SetupRoute
  BillsIdRoute: typeof BillsIdRouteWithChildren
  BillsNewRoute: typeof BillsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/new': {
      id: '/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof BillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id/edit': {
      id: '/bills/$id/edit'
      path: '/edit'
      fullPath: '/bills/$id/edit'
      preLoaderRoute: typeof BillsIdEditRouteImport
      parentRoute: typeof BillsIdRoute
    }
  }
}

interface BillsIdRouteChildren {
  BillsIdEditRoute: typeof BillsIdEditRoute
}

const BillsIdRouteChildren: BillsIdRouteChildren = {
  BillsIdEditRoute: BillsIdEditRoute,
}

const BillsIdRouteWithChildren =
  BillsIdRoute._addFileChildren(BillsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  SetupRoute: SetupRoute,
  BillsIdRoute: BillsIdRouteWithChildren,
  BillsNewRoute: BillsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
